sonar.projectKey=sonar-nest
sonar.projectName=sonar-nest
sonar.host.url=http://localhost:9000
sonar.sources=src
sonar.tests=src,test
sonar.test.inclusions=**/*.spec.ts
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=**/node_modules/**, dist/**, **/*.spec.ts
sonar.token=squ_796f0f1fd049e01b7273d81228a42c7206935182
